stages:
  - test

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:10.0
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    - apt-get install -y nodejs
  script:
    - 'dotnet restore --locked-mode'
    - 'dotnet test --configuration Release'